project:
  type: website

website:
  title: "Jesús Castro | Data Analyst"
  navbar:
    left:
      - href: index.md
        text: Inicio
      - href: proyectos.qmd # Reemplaza con tu archivo de proyectos si lo tienes
        text: Proyectos

format:
  html:
    theme: cosmo # Puedes cambiar 'cosmo' por otro tema de Quarto si lo deseas
    css: styles.css  # <-- ¡ESTA ES LA LÍNEA QUE ENLAZA TU DISEÑO!
    toc: true
